Feature/header
NickTsalyn/simply-chocolate pull request #16
Opened 2023-06-03 18:15 UTC by DarynaDvl

2023-06-03 20:35 UTC, NickTsalyn requested changes

2023-06-03 20:35 UTC, NickTsalyn commented on src/css/header.css
> +    font-weight: 500;
тут на табл, тільки на Home font-weight: 600px. Тупо, але шо є то є. зроби якийсь клас окреми і перебий на табл суто на ту одну li))

2023-06-03 20:35 UTC, NickTsalyn commented on src/css/header.css
> -    width: 100%;
тут я казав, обмеж ширину для моб і табл бо різна, 220 і 290px

2023-06-03 20:35 UTC, NickTsalyn commented on src/css/header.css
> +    padding-left: 50px;
добав ше нижній падінг auto))

2023-06-04 08:20 UTC, DarynaDvl commented on src/css/header.css
> +    font-weight: 500;
Виправила. Там font-weight змінюється не просто на Home, а при фокусі/ховері на будь-яке посилання меню

2023-06-04 08:21 UTC, DarynaDvl commented on src/css/header.css
> +    padding-left: 50px;
auto is not a valid value for padding property. Тому додала такий самий, як padding top, щоб гарно виглядало

2023-06-04 14:29 UTC, NickTsalyn approved these changes

2023-06-04 14:29 UTC, merged