Our products
NickTsalyn/simply-chocolate pull request #6
Opened 2023-06-02 21:53 UTC by olehpanadii

2023-06-03 14:18 UTC, NickTsalyn requested changes

2023-06-03 14:18 UTC, NickTsalyn commented on src/css/our-products.css
> +.section-title-products {
при адаптивці йдуть різні font-size та line-height. додай до медіа шоб перебити. тільки h2))

2023-06-04 09:04 UTC, olehpanadii commented on src/css/our-products.css
> +.section-title-products {
такі зміни на всіх h2 тому можливо саме цю медіа потрібно внести в основний  css?

2023-06-04 12:38 UTC, NickTsalyn approved these changes

2023-06-04 12:38 UTC, merged